---
- name: Restart cloudflared
  systemd:
    name: cloudflared
    state: restarted
  when: ansible_service_mgr == "systemd"

- name: Restart cloudflared (brew)
  command: brew services restart cloudflared
  listen: Restart cloudflared
  when: ansible_service_mgr == "launchd"
