---
- name: Restart node_exporter macOS
  command: brew services restart node_exporter
  when: ansible_facts['system'] == 'Darwin'
  listen: Restart node_exporter

- name: Restart node_exporter Linux
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true
  become: true
  when: ansible_facts['system'] == 'Linux'
  listen: Restart node_exporter
