---
- name: Restart node_exporter macOS
  shell: |
    launchctl unload {{ ansible_env.HOME }}/Library/LaunchAgents/com.node-exporter.plist
    launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/com.node-exporter.plist
  when: ansible_facts['system'] == 'Darwin'
  listen: Restart node_exporter

- name: Restart node_exporter Linux
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true
  become: true
  when: ansible_facts['system'] == 'Linux'
  listen: Restart node_exporter
