import fs from 'fs';
import os from 'os';
import path from 'path';
import { spawnSync } from 'child_process';
import yaml from 'js-yaml';
import {
  resolveFilePath,
  loadDeviceConfig,
  resolveFeatureRoles,
} from '../utils/deviceConfigLoader.js';

/**
 * Write a minimal Ansible inventory YAML scoped to a single host.
 *
 * Returns the path to the generated file.
 */
function generateScopedInventory(
  host: string,
  sshUser: string,
  tmpDir: string
): string {
  const inventory = {
    all: {
      hosts: {
        [host]: {
          ansible_user: sshUser,
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no',
        },
      },
    },
  };

  const content =
    '# Generated by iac-toolbox — do not edit manually\n' +
    yaml.dump(inventory, { lineWidth: -1, quotingType: "'" });

  const inventoryPath = path.join(tmpDir, `inventory-${host}.yml`);
  fs.writeFileSync(inventoryPath, content, 'utf-8');
  return inventoryPath;
}

/**
 * Configure (or update) the SSH config entry for a host.
 *
 * Appends a `Host <host>` block to ~/.ssh/config if one does not already
 * exist, or replaces the existing block.
 */
export function configureSshEntry(
  host: string,
  sshUser: string,
  sshKeyPath?: string
): void {
  const sshDir = path.join(os.homedir(), '.ssh');
  const sshConfigPath = path.join(sshDir, 'config');

  if (!fs.existsSync(sshDir)) {
    fs.mkdirSync(sshDir, { mode: 0o700, recursive: true });
  }

  const lines: string[] = [`Host ${host}`, `  User ${sshUser}`];

  if (sshKeyPath) {
    lines.push(`  IdentityFile ${sshKeyPath}`);
  }

  const block = lines.join('\n') + '\n';

  let existing = '';
  if (fs.existsSync(sshConfigPath)) {
    existing = fs.readFileSync(sshConfigPath, 'utf-8');
  }

  // Remove any existing block for this host (simple heuristic: match `Host <host>` lines)
  const hostHeaderRe = new RegExp(`^Host ${escapeRegex(host)}\\s*$`, 'm');

  if (hostHeaderRe.test(existing)) {
    // Replace the existing block.  A block runs until the next `Host ` line or EOF.
    const blockRe = new RegExp(
      `Host ${escapeRegex(host)}[^\\n]*\\n([ \\t]+[^\\n]*\\n)*`,
      'g'
    );
    existing = existing.replace(blockRe, '');
  }

  // Ensure the file ends with a newline before appending
  const separator = existing.length > 0 && !existing.endsWith('\n') ? '\n' : '';
  const updated = existing + separator + '\n' + block;

  fs.writeFileSync(sshConfigPath, updated, { mode: 0o600 });
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Run `iac-toolbox init --filePath <path>`.
 *
 * Reads host + ssh_user from the config and writes an SSH config entry.
 * Skips the interactive wizard.
 */
export async function runFilePathInit(filePath: string): Promise<void> {
  const resolvedPath = resolveFilePath(filePath);
  const config = loadDeviceConfig(resolvedPath);

  console.log(`Configuring SSH for ${config.host}...`);

  configureSshEntry(config.host, config.ssh_user);

  console.log('  SSH entry written to ~/.ssh/config');
  console.log(`    Host ${config.host}`);
  console.log(`    User ${config.ssh_user}`);
  console.log('');
  console.log('Done.');
}

/**
 * Run `iac-toolbox install --filePath <path>`.
 *
 * Loads DeviceConfig, resolves Ansible roles, generates a scoped inventory,
 * and runs ansible-playbook with the resolved roles.
 */
export async function runFilePathInstall(
  filePath: string,
  destination: string
): Promise<void> {
  const resolvedPath = resolveFilePath(filePath);
  const config = loadDeviceConfig(resolvedPath);
  const roles = resolveFeatureRoles(config.type, config.features);

  console.log(`Installing ${config.type} (${config.host})...`);
  console.log(`  Roles to apply: ${roles.join(', ')}`);

  // Generate a temporary scoped inventory
  const tmpDir = os.tmpdir();
  const inventoryPath = generateScopedInventory(
    config.host,
    config.ssh_user,
    tmpDir
  );

  // Locate the main playbook relative to destination
  const playbookPath = path.resolve(destination, 'playbooks', 'main.yml');

  if (!fs.existsSync(playbookPath)) {
    console.error(
      `Playbook not found at ${playbookPath}. Ensure infrastructure files are present.`
    );
    process.exit(1);
  }

  // Build ansible-playbook args
  const args: string[] = [
    playbookPath,
    '-i',
    inventoryPath,
    '--extra-vars',
    `ansible_roles="${roles.join(',')}"`,
  ];

  console.log(`\nRunning: ansible-playbook ${args.join(' ')}`);
  console.log('');

  const result = spawnSync('ansible-playbook', args, {
    stdio: 'inherit',
    encoding: 'utf-8',
  });

  // Clean up temp inventory
  try {
    fs.unlinkSync(inventoryPath);
  } catch {
    // best-effort cleanup
  }

  if (result.error) {
    console.error(`Failed to run ansible-playbook: ${result.error.message}`);
    process.exit(1);
  }

  process.exit(result.status ?? 1);
}
