import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';
import {
  setCredential,
  getCredential,
} from '../../loaders/credentials-loader.js';

const DEFAULT_VERSION = '2.323.0';
const DEFAULT_LABELS = 'self-hosted';
const DEFAULT_WORK_DIR = '~/.iac-toolbox/github-runner';

interface IacToolboxYaml {
  [key: string]: unknown;
  github_runner?: {
    enabled?: boolean;
    version?: string;
    repo_url?: string;
    labels?: string;
    work_dir?: string;
    [key: string]: unknown;
  };
}

export function loadGithubRunnerRepoUrl(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.github_runner?.repo_url;
}

export function loadGithubRunnerLabels(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.github_runner?.labels;
}

export function loadGithubRunnerToken(profile = 'default'): string | undefined {
  return getCredential('github_runner_token', profile);
}

export function updateGithubRunnerConfig(
  destination: string,
  repoUrl: string,
  token: string,
  labels: string,
  profile = 'default',
  filePath?: string
): void {
  const configPath = filePath
    ? path.resolve(filePath)
    : resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      config = {};
    }
  }

  // Save token to credentials store — never written to YAML.
  setCredential('github_runner_token', token, profile);

  config.github_runner = {
    ...(config.github_runner || {}),
    enabled: true,
    version: config.github_runner?.version ?? DEFAULT_VERSION,
    repo_url: repoUrl,
    labels: labels || DEFAULT_LABELS,
    work_dir: config.github_runner?.work_dir ?? DEFAULT_WORK_DIR,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
