---
- name: Reload systemd
  systemd:
    daemon_reload: true
  become: true
  when: ansible_service_mgr == "systemd"

- name: Restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
  become: true
  when: ansible_service_mgr == "systemd"
