---
- name: Restart node_exporter macOS
  shell: |
    launchctl unload {{ ansible_env.HOME }}/Library/LaunchAgents/com.node-exporter.plist
    launchctl load -w {{ ansible_env.HOME }}/Library/LaunchAgents/com.node-exporter.plist
  when: ansible_facts['system'] == 'Darwin'
  listen: Restart node_exporter

- name: Restart node_exporter Linux
  shell: docker compose restart node-exporter
  args:
    chdir: "{{ node_exporter_base_dir }}"
  when: ansible_facts['system'] == 'Linux'
  listen: Restart node_exporter
