import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';

const DEFAULT_DOMAIN = 'arize.iac-toolbox.com';
const DEFAULT_UI_PORT = 6006;

interface CloudflareDomainEntry {
  hostname: string;
  service_port: number;
  service: string;
}

interface IacToolboxYaml {
  [key: string]: unknown;
  arize_phoenix?: {
    enabled?: boolean;
    version?: string;
    ui_port?: number;
    db?: string;
    domain?: string;
    [key: string]: unknown;
  };
  cloudflare?: {
    enabled?: boolean;
    domains?: CloudflareDomainEntry[];
    [key: string]: unknown;
  };
}

export function loadArizeUiPort(
  destination: string,
  filePath?: string
): number | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.arize_phoenix?.ui_port;
}

export function loadArizeVersion(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.arize_phoenix?.version;
}

export function updateArizeConfig(
  destination: string,
  uiPort: number,
  version: string,
  filePath?: string
): void {
  const configPath = filePath
    ? path.resolve(filePath)
    : resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      config = {};
    }
  }

  const domain = DEFAULT_DOMAIN;

  config.arize_phoenix = {
    ...(config.arize_phoenix || {}),
    enabled: true,
    version,
    ui_port: uiPort,
    db: 'sqlite',
    domain,
  };

  // Write cloudflare.domains entry when cloudflare is enabled
  if (config.cloudflare?.enabled) {
    const domains: CloudflareDomainEntry[] = Array.isArray(
      config.cloudflare.domains
    )
      ? [...config.cloudflare.domains]
      : [];

    const alreadyPresent = domains.some((d) => d.hostname === domain);
    if (!alreadyPresent) {
      domains.push({
        hostname: domain,
        service_port: DEFAULT_UI_PORT,
        service: `http://localhost:${DEFAULT_UI_PORT}`,
      });
    }

    config.cloudflare = {
      ...config.cloudflare,
      domains,
    };
  }

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
