import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  loki?: {
    enabled?: boolean;
    port?: number;
    retention_hours?: number;
    [key: string]: unknown;
  };
}

export function loadLokiPort(
  destination: string,
  filePath?: string
): number | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.loki?.port;
}

export function loadLokiRetentionHours(
  destination: string,
  filePath?: string
): number | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.loki?.retention_hours;
}

export function updateLokiConfig(
  destination: string,
  port: number,
  retentionHours: number,
  filePath?: string
): void {
  const configPath = filePath
    ? path.resolve(filePath)
    : resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      config = {};
    }
  }

  config.loki = {
    ...(config.loki || {}),
    enabled: true,
    port,
    retention_hours: retentionHours,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
