import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';
import {
  setCredential,
  getCredential,
} from '../../loaders/credentials-loader.js';

interface TailscaleSection {
  enabled?: boolean;
  hostname?: string;
  [key: string]: unknown;
}

interface IacToolboxYaml {
  [key: string]: unknown;
  tailscale?: TailscaleSection;
}

/**
 * Load the tailscale section from iac-toolbox.yml.
 * Returns undefined if the section is not set.
 */
export function loadTailscaleConfig(
  destination: string,
  filePath?: string
): TailscaleSection | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.tailscale as TailscaleSection | undefined;
}

/**
 * Load the Tailscale auth key from the credentials store.
 */
export function loadTailscaleAuthKey(profile = 'default'): string | undefined {
  return getCredential('tailscale_auth_key', profile);
}

/**
 * Update the tailscale section of iac-toolbox.yml and save auth key
 * to the credentials store.
 *
 * The auth key is never written to the YAML config file.
 */
export function updateTailscaleConfig(
  destination: string,
  options: {
    authKey: string;
    hostname: string;
  },
  profile = 'default',
  filePath?: string
): void {
  const configPath = filePath
    ? path.resolve(filePath)
    : resolveConfigPath(destination);

  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      config = {};
    }
  }

  // Save auth key to credentials store — never written to YAML.
  setCredential('tailscale_auth_key', options.authKey, profile);

  config.tailscale = {
    ...(config.tailscale || {}),
    enabled: true,
    hostname: options.hostname,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}

export type { TailscaleSection };
