import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  grafana_alloy?: {
    alloy_remote_write_url?: string;
    enabled?: boolean;
    [key: string]: unknown;
  };
  node_exporter?: { enabled?: boolean; [key: string]: unknown };
  cadvisor?: { enabled?: boolean; [key: string]: unknown };
}

/**
 * Load the alloy_remote_write_url from iac-toolbox.yml.
 * Returns an empty object if not set.
 */
export function loadMetricsAgentConfig(destination: string): {
  alloy_remote_write_url?: string;
} {
  const config = loadIacToolboxYaml(destination) as IacToolboxYaml;
  return {
    alloy_remote_write_url: config.grafana_alloy?.alloy_remote_write_url,
  };
}

/**
 * Update the grafana_alloy, node_exporter, and cadvisor
 * sections of iac-toolbox.yml.
 *
 * Writes:
 *   grafana_alloy.enabled = true
 *   grafana_alloy.alloy_remote_write_url = <prometheusRemoteWriteUrl>
 *   node_exporter.enabled = true
 *   cadvisor.enabled = true
 *
 * Preserves the rest of the file content.
 */
export function updateMetricsAgentConfig(
  destination: string,
  prometheusRemoteWriteUrl: string
): void {
  const configPath = resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      config =
        (yaml.load(fs.readFileSync(configPath, 'utf-8')) as IacToolboxYaml) ||
        {};
    } catch {
      config = {};
    }
  }

  config.grafana_alloy = {
    ...(config.grafana_alloy || {}),
    enabled: true,
    alloy_remote_write_url: prometheusRemoteWriteUrl,
  };

  config.node_exporter = { ...(config.node_exporter || {}), enabled: true };
  config.cadvisor = { ...(config.cadvisor || {}), enabled: true };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
