---
- name: Create Terraform destination directory
  ansible.builtin.file:
    path: "{{ http_status_code_alerts.terraform_dest }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Render providers.tf
  ansible.builtin.template:
    src: providers.tf.j2
    dest: "{{ http_status_code_alerts.terraform_dest }}/providers.tf"
  delegate_to: localhost

- name: Render variables.tf
  ansible.builtin.template:
    src: variables.tf.j2
    dest: "{{ http_status_code_alerts.terraform_dest }}/variables.tf"
  delegate_to: localhost

- name: Render terraform.tfvars
  ansible.builtin.template:
    src: terraform.tfvars.j2
    dest: "{{ http_status_code_alerts.terraform_dest }}/terraform.tfvars"
    mode: '0600'
  delegate_to: localhost

- name: Add terraform.tfvars to .gitignore
  ansible.builtin.lineinfile:
    path: "{{ http_status_code_alerts.terraform_dest }}/.gitignore"
    line: "terraform.tfvars"
    create: true
  delegate_to: localhost

- name: Render main.tf
  ansible.builtin.template:
    src: main.tf.j2
    dest: "{{ http_status_code_alerts.terraform_dest }}/main.tf"
  delegate_to: localhost

- name: Terraform init
  ansible.builtin.command:
    cmd: terraform init
    chdir: "{{ http_status_code_alerts.terraform_dest }}"
  changed_when: false
  delegate_to: localhost

- name: Terraform apply
  ansible.builtin.command:
    cmd: terraform apply -auto-approve
    chdir: "{{ http_status_code_alerts.terraform_dest }}"
  changed_when: true
  delegate_to: localhost
