import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  container_metrics_alerts?: {
    enabled?: boolean;
    terraform_dest?: string;
    service_name?: string;
    [key: string]: unknown;
  };
}

/**
 * Load whether container metrics alerts are enabled from iac-toolbox.yml.
 * Returns undefined if not set.
 */
export function loadContainerMetricsAlertsEnabled(
  destination: string,
  filePath?: string
): boolean | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.container_metrics_alerts?.enabled;
}

/**
 * Load the container_metrics_alerts.service_name from iac-toolbox.yml.
 * Returns undefined if not set.
 */
export function loadContainerMetricsAlertsServiceName(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.container_metrics_alerts?.service_name;
}

/**
 * Load the container_metrics_alerts.terraform_dest from iac-toolbox.yml.
 * Returns undefined if not set.
 */
export function loadContainerMetricsAlertsTerraformDest(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.container_metrics_alerts?.terraform_dest;
}

/**
 * Update the container_metrics_alerts.enabled key in iac-toolbox.yml.
 * Preserves the rest of the file content.
 */
export function updateContainerMetricsAlertsConfig(
  destination: string,
  enabled: boolean,
  filePath?: string
): void {
  const configPath = filePath ?? resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      config =
        (yaml.load(fs.readFileSync(configPath, 'utf-8')) as IacToolboxYaml) ||
        {};
    } catch {
      config = {};
    }
  }

  config.container_metrics_alerts = {
    ...(config.container_metrics_alerts || {}),
    enabled,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}

/**
 * Write the container_metrics_alerts.service_name to iac-toolbox.yml.
 * Preserves the rest of the file content.
 */
export function updateContainerMetricsAlertsServiceName(
  destination: string,
  serviceName: string,
  filePath?: string
): void {
  const configPath = filePath ?? resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      config =
        (yaml.load(fs.readFileSync(configPath, 'utf-8')) as IacToolboxYaml) ||
        {};
    } catch {
      config = {};
    }
  }

  config.container_metrics_alerts = {
    ...(config.container_metrics_alerts || {}),
    service_name: serviceName,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}

/**
 * Write the container_metrics_alerts.terraform_dest to iac-toolbox.yml.
 * Preserves the rest of the file content.
 */
export function updateContainerMetricsAlertsTerraformDest(
  destination: string,
  terraformDest: string,
  filePath?: string
): void {
  const configPath = filePath ?? resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      config =
        (yaml.load(fs.readFileSync(configPath, 'utf-8')) as IacToolboxYaml) ||
        {};
    } catch {
      config = {};
    }
  }

  config.container_metrics_alerts = {
    ...(config.container_metrics_alerts || {}),
    terraform_dest: terraformDest,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
