---
- name: Reload systemd
  systemd:
    daemon_reload: true
  become: true
  when: ansible_service_mgr == "systemd"

- name: Restart grafana-alloy
  systemd:
    name: grafana-alloy
    state: restarted
  become: true
  when: ansible_service_mgr == "systemd"
