import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  prometheus?: {
    // grafana_url was removed — now derived by Ansible from grafana.domain
    domain?: string;
    [key: string]: unknown;
  };
}

/**
 * Load the prometheus.grafana_url from iac-toolbox.yml.
 * Returns undefined if the key is not set.
 * @deprecated grafana_url is no longer stored — it is derived by Ansible from grafana.domain
 */
export function loadPrometheusGrafanaUrl(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml & {
    prometheus?: { grafana_url?: string };
  };
  return config.prometheus?.grafana_url;
}

/**
 * Load the prometheus.domain from iac-toolbox.yml.
 * Returns undefined if the key is not set.
 */
export function loadPrometheusDomain(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.prometheus?.domain as string | undefined;
}

/**
 * Update the prometheus section of iac-toolbox.yml with domain.
 *
 * grafana_url is derived automatically by Ansible from grafana.domain — not stored here.
 *
 * Preserves the rest of the file content.
 */
export function updatePrometheusConfig(
  destination: string,
  domain: string,
  filePath?: string
): void {
  const configPath = filePath
    ? path.resolve(filePath)
    : resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      config = {};
    }
  }

  // Merge prometheus section — grafana_url is derived by Ansible, not stored here
  config.prometheus = {
    ...(config.prometheus || {}),
    domain,
  };

  // Ensure directory exists
  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
