import { describe, it, expect, beforeEach, afterEach } from '@jest/globals';
import fs from 'fs';
import path from 'path';
import os from 'os';
import yaml from 'js-yaml';
import {
  loadPrometheusGrafanaUrl,
  updatePrometheusConfig,
} from './prometheus-config.js';

// ---------------------------------------------------------------------------
// Use real filesystem with temp directories instead of mocking fs,
// since jest.mock('fs') does not work reliably with ESM modules.
// ---------------------------------------------------------------------------

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'prometheus-config-test-'));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// loadPrometheusGrafanaUrl
// ---------------------------------------------------------------------------
describe('loadPrometheusGrafanaUrl', () => {
  it('returns undefined when config file does not exist', () => {
    const subDir = path.join(tmpDir, 'nonexistent');
    const result = loadPrometheusGrafanaUrl(subDir);
    expect(result).toBeUndefined();
  });

  it('returns undefined when prometheus section is absent', () => {
    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    fs.writeFileSync(configPath, yaml.dump({ grafana: { enabled: true } }));

    const result = loadPrometheusGrafanaUrl(tmpDir);
    expect(result).toBeUndefined();
  });

  it('returns the grafana_url when set', () => {
    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    fs.writeFileSync(
      configPath,
      yaml.dump({
        prometheus: { grafana_url: 'http://myhost:4000' },
      })
    );

    const result = loadPrometheusGrafanaUrl(tmpDir);
    expect(result).toBe('http://myhost:4000');
  });
});

// ---------------------------------------------------------------------------
// updatePrometheusConfig
// ---------------------------------------------------------------------------
describe('updatePrometheusConfig', () => {
  it('creates new config with prometheus.domain when file does not exist', () => {
    updatePrometheusConfig(tmpDir, 'prometheus.iac-toolbox.com');

    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    expect(fs.existsSync(configPath)).toBe(true);

    const content = fs.readFileSync(configPath, 'utf-8');
    expect(content).toContain('prometheus.iac-toolbox.com');
  });

  it('does not write grafana_url', () => {
    updatePrometheusConfig(tmpDir, 'prometheus.iac-toolbox.com');

    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    const content = fs.readFileSync(configPath, 'utf-8');
    expect(content).not.toContain('grafana_url');
  });

  it('preserves existing config and merges prometheus section', () => {
    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    const existing = yaml.dump({
      grafana: { enabled: true, admin_user: 'admin' },
      prometheus: { enabled: true, port: 9090 },
    });
    fs.writeFileSync(configPath, existing);

    updatePrometheusConfig(tmpDir, 'prometheus.iac-toolbox.com');

    const content = fs.readFileSync(configPath, 'utf-8');
    const parsed = yaml.load(content) as Record<string, unknown>;

    // Should preserve grafana section
    expect(content).toContain('grafana');
    // Should preserve existing prometheus keys
    expect((parsed.prometheus as Record<string, unknown>).port).toBe(9090);
    // Should have new domain
    expect((parsed.prometheus as Record<string, unknown>).domain).toBe(
      'prometheus.iac-toolbox.com'
    );
  });

  it('adds header comment to generated config', () => {
    updatePrometheusConfig(tmpDir, 'prometheus.iac-toolbox.com');

    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    const content = fs.readFileSync(configPath, 'utf-8');
    expect(content).toContain('Generated by iac-toolbox');
    expect(content).toContain('no secrets');
  });
});
