import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';
import { saveCredentials } from '../../loaders/credentials-loader.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  grafana_pagerduty?: {
    enabled?: boolean;
    service_region?: string;
    service_name?: string;
    terraform_dest?: string;
    pagerduty_token?: string;
    [key: string]: unknown;
  };
}

/**
 * Load the grafana_pagerduty section from iac-toolbox.yml.
 * Returns undefined if not set.
 */
export function loadGrafanaPagerdutyConfig(
  destination: string,
  filePath?: string
): IacToolboxYaml['grafana_pagerduty'] {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.grafana_pagerduty;
}

/**
 * Write the grafana_pagerduty section to iac-toolbox.yml.
 * Preserves the rest of the file content.
 * Sensitive values (pagerduty_token) are NOT written here — use saveGrafanaPagerdutyToken instead.
 */
export function updateGrafanaPagerdutyConfig(
  destination: string,
  enabled: boolean,
  serviceRegion: string,
  serviceName: string,
  terraformDest: string,
  filePath?: string
): void {
  const configPath = filePath ?? resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      config =
        (yaml.load(fs.readFileSync(configPath, 'utf-8')) as IacToolboxYaml) ||
        {};
    } catch {
      config = {};
    }
  }

  config.grafana_pagerduty = {
    ...(config.grafana_pagerduty || {}),
    enabled,
    service_region: serviceRegion,
    service_name: serviceName,
    terraform_dest: terraformDest,
    ...(enabled ? { pagerduty_token: '{{ pagerduty_token }}' } : {}),
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}

/**
 * Save the PagerDuty API token to the credentials store.
 * The token is stored under the key `pagerduty_token` and is referenced
 * in iac-toolbox.yml as `{{ pagerduty_token }}`.
 */
export function saveGrafanaPagerdutyToken(
  token: string,
  profile: string = 'default'
): void {
  saveCredentials({ pagerduty_token: token }, profile);
}
