import path from 'path';
import { IacToolboxYaml, resolveConfigPath } from 'src/loaders/yaml-loader.js';
import fs from 'fs';
import yaml from 'js-yaml';
/**
 * Update the grafana section of iac-toolbox.yml with the admin_user
 * and the Ansible variable reference for admin_password.
 *
 * Preserves the rest of the file content.
 */
export function updateGrafanaConfig(
  destination: string,
  adminUser: string,
  filePath?: string
): void {
  const configPath = filePath ?? resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      config = {};
    }
  }

  // Merge grafana section
  config.grafana = {
    ...(config.grafana || {}),
    enabled: true,
    admin_user: adminUser,
    admin_password: '{{ grafana_admin_password }}',
  };

  // Ensure directory exists
  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
