import { describe, it, expect, beforeEach, afterEach } from '@jest/globals';
import fs from 'fs';
import path from 'path';
import os from 'os';
import yaml from 'js-yaml';
import {
  resolveConfigPath,
  loadIacToolboxYaml,
} from 'src/loaders/yaml-loader.js';
import { updateGrafanaConfig } from './grafana-config.js';

// ---------------------------------------------------------------------------
// Use real filesystem with temp directories instead of mocking fs,
// since jest.mock('fs') does not work reliably with ESM modules.
// ---------------------------------------------------------------------------

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'grafana-config-test-'));
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

// ---------------------------------------------------------------------------
// resolveConfigPath
// ---------------------------------------------------------------------------
describe('resolveConfigPath', () => {
  it('returns primary path when file exists at destination', () => {
    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    fs.writeFileSync(configPath, 'test: true\n');

    const result = resolveConfigPath(tmpDir);
    expect(result).toBe(configPath);
  });

  it('returns primary path as default when file does not exist', () => {
    // tmpDir exists but has no iac-toolbox.yml
    const result = resolveConfigPath(tmpDir);
    // Should fall through to default primary path since home path also won't exist
    // The exact behavior depends on whether ~/.iac-toolbox/iac-toolbox.yml exists
    // but we can verify the result is a valid path string
    expect(result).toContain('iac-toolbox.yml');
  });
});

// ---------------------------------------------------------------------------
// loadIacToolboxYaml
// ---------------------------------------------------------------------------
describe('loadIacToolboxYaml', () => {
  it('returns empty object when config file does not exist', () => {
    const subDir = path.join(tmpDir, 'nonexistent');
    // subDir doesn't exist, and neither does ~/.iac-toolbox/iac-toolbox.yml
    // in a controlled way, so we use a unique path
    const result = loadIacToolboxYaml(subDir);
    expect(result).toEqual({});
  });

  it('parses valid YAML config file', () => {
    const configData = { grafana: { enabled: true, admin_user: 'admin' } };
    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    fs.writeFileSync(configPath, yaml.dump(configData));

    const result = loadIacToolboxYaml(tmpDir);
    expect(result).toEqual(configData);
  });

  it('returns empty object on invalid YAML', () => {
    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    // Write something that yaml.load returns null for
    fs.writeFileSync(configPath, '');

    const result = loadIacToolboxYaml(tmpDir);
    expect(result).toEqual({});
  });
});

// ---------------------------------------------------------------------------
// updateGrafanaConfig
// ---------------------------------------------------------------------------
describe('updateGrafanaConfig', () => {
  it('creates new config with grafana section when file does not exist', () => {
    updateGrafanaConfig(tmpDir, 'myadmin');

    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    expect(fs.existsSync(configPath)).toBe(true);

    const content = fs.readFileSync(configPath, 'utf-8');
    expect(content).toContain('admin_user');
    expect(content).toContain('myadmin');
    expect(content).toContain('grafana_admin_password');
    expect(content).toContain('enabled: true');
  });

  it('preserves existing config and merges grafana section', () => {
    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    const existing = yaml.dump({
      vault: { enabled: true },
      grafana: { enabled: false, custom_key: 'keep' },
    });
    fs.writeFileSync(configPath, existing);

    updateGrafanaConfig(tmpDir, 'newadmin');

    const content = fs.readFileSync(configPath, 'utf-8');
    // Should preserve vault section
    expect(content).toContain('vault');
    // Should update grafana section
    expect(content).toContain('newadmin');
    expect(content).toContain('enabled: true');
    // Should preserve custom_key from existing grafana config
    expect(content).toContain('custom_key');
  });

  it('sets admin_password to Ansible variable reference', () => {
    updateGrafanaConfig(tmpDir, 'admin');

    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    const content = fs.readFileSync(configPath, 'utf-8');
    expect(content).toContain('{{ grafana_admin_password }}');
  });

  it('adds header comment to generated config', () => {
    updateGrafanaConfig(tmpDir, 'admin');

    const configPath = path.join(tmpDir, 'iac-toolbox.yml');
    const content = fs.readFileSync(configPath, 'utf-8');
    expect(content).toContain('Generated by iac-toolbox');
    expect(content).toContain('no secrets');
  });
});
