import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  resolveConfigPath,
  loadIacToolboxYaml,
} from '../grafana/grafana-config.js';

interface CloudflareDomain {
  hostname: string;
  service_port: number;
  service: string;
}

interface CloudflareSection {
  enabled?: boolean;
  mode?: string;
  account_id?: string;
  zone_id?: string;
  tunnel_name?: string;
  cloudflare_api_token?: string;
  domains?: CloudflareDomain[];
  [key: string]: unknown;
}

interface IacToolboxYaml {
  [key: string]: unknown;
  cloudflare?: CloudflareSection;
}

/**
 * Load the cloudflare section from iac-toolbox.yml.
 * Returns undefined if the section is not set.
 */
export function loadCloudflareConfig(
  destination: string
): CloudflareSection | undefined {
  const config = loadIacToolboxYaml(destination) as IacToolboxYaml;
  return config.cloudflare as CloudflareSection | undefined;
}

/**
 * Update the cloudflare section of iac-toolbox.yml.
 *
 * Writes account_id, zone_id, tunnel_name, domains, and the Ansible
 * variable reference for the API token. Preserves the rest of the file.
 */
export function updateCloudflareConfig(
  destination: string,
  options: {
    accountId: string;
    zoneId: string;
    tunnelName: string;
    hostname: string;
    servicePort: number;
  }
): void {
  const configPath = resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      config = {};
    }
  }

  // Merge cloudflare section
  config.cloudflare = {
    ...(config.cloudflare || {}),
    enabled: true,
    mode: 'api',
    account_id: options.accountId,
    zone_id: options.zoneId,
    tunnel_name: options.tunnelName,
    cloudflare_api_token: '{{ cloudflare_api_token }}',
    domains: [
      {
        hostname: options.hostname,
        service_port: options.servicePort,
        service: `http://localhost:${options.servicePort}`,
      },
    ],
  };

  // Ensure directory exists
  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}

export type { CloudflareSection, CloudflareDomain };
