---
# Default variables for prometheus role
prometheus:
  enabled: true
  version: "latest"
  base_dir: "{{ ansible_env.HOME }}/.iac-toolbox/observability"
  port: 9090
  scrape_interval: "15s"
  retention: "15d"

node_exporter:
  version: "latest"
  port: 9100
