---
# Default variables for prometheus role
prometheus:
  enabled: false
  version: "latest"
  base_dir: "{{ ansible_env.HOME }}/.iac-toolbox/prometheus"
  port: 9090
  scrape_interval: "15s"
  retention: "15d"
  remote_write_receiver: true
