import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import { resolveConfigPath, loadIacToolboxYaml } from './grafanaConfig.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  cadvisor?: { enabled?: boolean; [key: string]: unknown };
}

/**
 * Check whether cAdvisor is enabled in iac-toolbox.yml.
 * Returns true only if cadvisor.enabled is explicitly set to true.
 */
export function isCAdvisorEnabled(destination: string): boolean {
  const config = loadIacToolboxYaml(destination) as IacToolboxYaml;
  return config.cadvisor?.enabled === true;
}

/**
 * Write cadvisor.enabled = true to iac-toolbox.yml.
 * Preserves all other content in the file.
 */
export function updateCAdvisorConfig(destination: string, filePath?: string): void {
  const configPath = filePath ?? resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      config =
        (yaml.load(fs.readFileSync(configPath, 'utf-8')) as IacToolboxYaml) ||
        {};
    } catch {
      config = {};
    }
  }

  config.cadvisor = { ...(config.cadvisor || {}), enabled: true };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
