import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

interface IacToolboxYaml {
  [key: string]: unknown;
  grafana?: {
    enabled?: boolean;
    admin_user?: string;
    admin_password?: string;
    [key: string]: unknown;
  };
}

/**
 * Resolve the path to iac-toolbox.yml.
 *
 * Priority:
 * 1. <destination>/iac-toolbox.yml
 * 2. ~/.iac-toolbox/iac-toolbox.yml
 */
export function resolveConfigPath(destination: string): string {
  const primary = path.join(destination, 'iac-toolbox.yml');
  if (fs.existsSync(primary)) {
    return primary;
  }

  const homePath = path.join(
    process.env.HOME || process.env.USERPROFILE || '~',
    '.iac-toolbox',
    'iac-toolbox.yml'
  );
  if (fs.existsSync(homePath)) {
    return homePath;
  }

  // Default to primary (will be created)
  return primary;
}

/**
 * Load and parse the iac-toolbox.yml file.
 * Returns an empty object if the file does not exist.
 */
export function loadIacToolboxYaml(destination: string, filePath?: string): IacToolboxYaml {
  const configPath = filePath ?? resolveConfigPath(destination);
  if (!fs.existsSync(configPath)) {
    return {};
  }

  try {
    const content = fs.readFileSync(configPath, 'utf-8');
    return (yaml.load(content) as IacToolboxYaml) || {};
  } catch {
    return {};
  }
}

/**
 * Update the grafana section of iac-toolbox.yml with the admin_user
 * and the Ansible variable reference for admin_password.
 *
 * Preserves the rest of the file content.
 */
export function updateGrafanaConfig(
  destination: string,
  adminUser: string,
  filePath?: string
): void {
  const configPath = filePath ?? resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      config = {};
    }
  }

  // Merge grafana section
  config.grafana = {
    ...(config.grafana || {}),
    enabled: true,
    admin_user: adminUser,
    admin_password: '{{ grafana_admin_password }}',
  };

  // Ensure directory exists
  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
