import fs from 'fs/promises';
import path from 'path';
import type { GitHubBuildWorkflowConfig } from '../components/GitHubBuildWorkflowDialog.js';
import type { CloudflareConfig } from '../components/CloudflareConfigDialog.js';
import type { VaultConfig } from '../components/VaultConfigDialog.js';
import type { GrafanaConfig } from '../components/GrafanaConfigDialog.js';
import type { DeviceProfile } from '../components/DeviceProfileDialog.js';
import type { ObservabilityRemoteConfig } from '../components/ObservabilityRemoteDialog.js';

interface IacToolboxYamlConfig {
  selectedIntegrations: string[];
  deviceProfile?: DeviceProfile;
  githubBuildWorkflow?: GitHubBuildWorkflowConfig;
  cloudflare?: CloudflareConfig;
  vault?: VaultConfig;
  grafana?: GrafanaConfig;
  observabilityRemote?: ObservabilityRemoteConfig | null;
}

/**
 * Generate the contents of iac-toolbox.yml.
 *
 * All integrations are represented in the output regardless of selection.
 * Disabled integrations default to `enabled: false` with a "coming soon" comment.
 * Sensitive values are replaced with variable references.
 */
export function generateIacToolboxYaml(config: IacToolboxYamlConfig): string {
  const lines: string[] = [
    '# Generated by iac-toolbox init',
    '# Safe to commit — no secrets stored here',
    '',
  ];

  // Device profile
  if (config.deviceProfile) {
    lines.push('device:');
    lines.push(`  profile: "${config.deviceProfile}"`);
    lines.push('');
  }

  // Observability remote (app-server mode)
  if (config.observabilityRemote) {
    lines.push('observability:');
    lines.push('  remote: true');
    lines.push(
      `  prometheus_host: "${config.observabilityRemote.prometheusHost}"`
    );
    lines.push(
      `  prometheus_port: ${config.observabilityRemote.prometheusPort}`
    );
    lines.push(`  loki_host: "${config.observabilityRemote.lokiHost}"`);
    lines.push(`  loki_port: ${config.observabilityRemote.lokiPort}`);
    lines.push('');
  }

  lines.push('docker:');
  lines.push('  enabled: true # always installed, not configurable');
  lines.push('');

  // GitHub Build Workflow
  if (
    config.selectedIntegrations.includes('github_build_workflow') &&
    config.githubBuildWorkflow
  ) {
    lines.push('github_build_workflow:');
    lines.push('  enabled: true');
    lines.push(
      `  docker_hub_username: "${config.githubBuildWorkflow.dockerHubUsername}"`
    );
    lines.push(
      `  docker_image_name: "${config.githubBuildWorkflow.dockerImageName}"`
    );
    lines.push(
      '  docker_hub_token: "{{ docker_hub_token }}" # injected by CLI at deploy time'
    );
  } else {
    lines.push('github_build_workflow:');
    lines.push('  enabled: false');
  }

  // Coming soon integrations — always disabled
  lines.push('');
  lines.push('github_runner:');
  lines.push('  enabled: false # coming soon');
  lines.push('');

  // Cloudflare
  if (config.selectedIntegrations.includes('cloudflare') && config.cloudflare) {
    const cf = config.cloudflare;
    lines.push('cloudflare:');
    lines.push('  enabled: true');
    lines.push(`  mode: "${cf.mode}"`);
    lines.push(`  tunnel_name: "${cf.tunnelName}"`);
    lines.push(`  account_id: "${cf.accountId}"`);
    lines.push(`  zone_id: "${cf.zoneId}"`);
    lines.push(
      '  cloudflare_api_token: "{{ cloudflare_api_token }}" # injected by CLI at deploy time'
    );
    lines.push('  domains:');
    lines.push(`    - hostname: "${cf.hostname}"`);
    lines.push(`      service_port: ${cf.servicePort}`);
    lines.push(`      service: "http://localhost:${cf.servicePort}"`);
  } else {
    lines.push('cloudflare:');
    lines.push('  enabled: false # coming soon');
  }
  lines.push('');

  // Vault
  if (config.selectedIntegrations.includes('vault') && config.vault) {
    const v = config.vault;
    lines.push('vault:');
    lines.push('  enabled: true');
    lines.push(`  version: "${v.version}"`);
    lines.push(`  port: ${v.port}`);
    lines.push(`  enable_kv: ${v.enableKv}`);
    lines.push(`  enable_audit: ${v.enableAudit}`);
    if (v.domain) {
      lines.push(`  domain: "${v.domain}"`);
    }
  } else {
    lines.push('vault:');
    lines.push('  enabled: false # coming soon');
  }
  lines.push('');

  // Grafana
  if (config.selectedIntegrations.includes('grafana') && config.grafana) {
    const g = config.grafana;
    lines.push('grafana:');
    lines.push('  enabled: true');
    lines.push('  version: "latest"');
    lines.push('  port: 3000');
    lines.push('  admin_user: "admin"');
    lines.push(
      '  admin_password: "{{ grafana_admin_password }}" # injected by CLI at deploy time'
    );
    if (g.domain) {
      lines.push(`  domain: "${g.domain}"`);
    }
  } else {
    lines.push('grafana:');
    lines.push('  enabled: false # coming soon');
  }
  lines.push('');

  // Prometheus
  if (config.selectedIntegrations.includes('prometheus')) {
    lines.push('prometheus:');
    lines.push('  enabled: true');
    lines.push('  version: "latest"');
    lines.push('  port: 9090');
    lines.push('  scrape_interval: "15s"');
    lines.push('  retention: "15d"');
  } else {
    lines.push('prometheus:');
    lines.push('  enabled: false');
  }
  lines.push('');

  // node_exporter and alloy are internal supporting services for Grafana
  if (config.selectedIntegrations.includes('grafana') && config.grafana) {
    lines.push('node_exporter:');
    lines.push('  version: "latest"');
    lines.push('  port: 9100');
    lines.push('');
  }

  // Loki
  if (config.selectedIntegrations.includes('loki')) {
    lines.push('loki:');
    lines.push('  enabled: true');
    lines.push('  version: "latest"');
    lines.push('  port: 3100');
    lines.push('  retention_hours: 168');
  } else {
    lines.push('loki:');
    lines.push('  enabled: false');
  }
  lines.push('');

  if (config.selectedIntegrations.includes('grafana') && config.grafana) {
    lines.push('alloy:');
    lines.push('  enabled: true');
    lines.push('  version: "latest"');
    lines.push('  port: 12345');
    lines.push('');
  }

  lines.push('pagerduty:');
  lines.push('  enabled: false # coming soon');
  lines.push('');

  return lines.join('\n');
}

/**
 * Write iac-toolbox.yml to the specified directory.
 */
export async function writeIacToolboxYaml(
  directory: string,
  config: IacToolboxYamlConfig
): Promise<string> {
  const content = generateIacToolboxYaml(config);
  const filePath = path.join(directory, 'iac-toolbox.yml');
  await fs.writeFile(filePath, content, 'utf-8');
  return filePath;
}

export type { IacToolboxYamlConfig };
