import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import { resolveConfigPath, loadIacToolboxYaml } from './grafanaConfig.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  grafana_alloy?: { alloy_remote_write_url?: string; [key: string]: unknown };
  node_exporter?: { enabled?: boolean; [key: string]: unknown };
}

/**
 * Load the grafana_alloy.alloy_remote_write_url from iac-toolbox.yml.
 * Returns undefined if the key is not set.
 */
export function loadMetricsAgentRemoteWriteUrl(
  destination: string
): string | undefined {
  const config = loadIacToolboxYaml(destination) as IacToolboxYaml;
  return config.grafana_alloy?.alloy_remote_write_url as string | undefined;
}

/**
 * Update the node_exporter and grafana_alloy sections of iac-toolbox.yml.
 *
 * Writes:
 *   node_exporter.enabled = true
 *   grafana_alloy.enabled = true
 *   grafana_alloy.alloy_remote_write_url = <remoteWriteUrl>
 *
 * Preserves the rest of the file content.
 */
export function updateMetricsAgentConfig(
  destination: string,
  remoteWriteUrl: string
): void {
  const configPath = resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      config =
        (yaml.load(fs.readFileSync(configPath, 'utf-8')) as IacToolboxYaml) ||
        {};
    } catch {
      config = {};
    }
  }

  config.node_exporter = { ...(config.node_exporter || {}), enabled: true };
  config.grafana_alloy = {
    ...(config.grafana_alloy || {}),
    enabled: true,
    alloy_remote_write_url: remoteWriteUrl,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
