import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import { resolveConfigPath, loadIacToolboxYaml } from './grafanaConfig.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  prometheus?: {
    grafana_url?: string;
    domain?: string;
    [key: string]: unknown;
  };
  grafana?: {
    port?: number;
    [key: string]: unknown;
  };
}

/**
 * Load the prometheus.grafana_url from iac-toolbox.yml.
 * Returns undefined if the key is not set.
 */
export function loadPrometheusGrafanaUrl(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.prometheus?.grafana_url as string | undefined;
}

/**
 * Load the prometheus.domain from iac-toolbox.yml.
 * Returns undefined if the key is not set.
 */
export function loadPrometheusDomain(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.prometheus?.domain as string | undefined;
}

/**
 * Update the prometheus section of iac-toolbox.yml with grafana_url and domain.
 *
 * Also writes `grafana.port` when the URL uses a non-default port,
 * so the Ansible role picks it up via `@iac-toolbox.yml`.
 *
 * Preserves the rest of the file content.
 */
export function updatePrometheusConfig(
  destination: string,
  grafanaUrl: string,
  domain: string,
  filePath?: string
): void {
  const configPath = filePath
    ? path.resolve(filePath)
    : resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      config = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      config = {};
    }
  }

  // Merge prometheus section
  config.prometheus = {
    ...(config.prometheus || {}),
    grafana_url: grafanaUrl,
    domain,
  };

  // Parse port from URL and write to grafana.port if non-default
  try {
    const parsed = new URL(grafanaUrl);
    const port = parsed.port;
    if (port && port !== '3000') {
      config.grafana = {
        ...(config.grafana || {}),
        port: parseInt(port, 10),
      };
    }
  } catch {
    // Invalid URL — skip port extraction
  }

  // Ensure directory exists
  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
