---
# ============================================
# IaC Toolbox - Grafana Playbook
# ============================================

- name: Deploy Grafana
  hosts: all
  become: false
  roles:
    - role: grafana
      when: grafana is defined and grafana.enabled
