---
# ============================================
# IaC Toolbox - Loki Playbook
# ============================================

- name: Deploy Loki
  hosts: all
  become: false
  roles:
    - role: loki
      when: loki is defined and loki.enabled
