import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  threshold_alerts?: {
    enabled?: boolean;
    threshold_alerts_terraform_dest?: string;
    memory_critical_threshold?: number;
    cpu_critical_threshold?: number;
    disk_critical_threshold?: number;
    [key: string]: unknown;
  };
}

/**
 * Load the threshold_alerts_terraform_dest top-level variable from iac-toolbox.yml.
 * Returns undefined if not set.
 */
export function loadThresholdAlertsTerraformDest(
  destination: string,
  filePath?: string
): string | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.threshold_alerts?.threshold_alerts_terraform_dest;
}

/**
 * Write the threshold_alerts_terraform_dest top-level variable to iac-toolbox.yml.
 * Preserves the rest of the file content.
 */
export function updateThresholdAlertsTerraformDest(
  destination: string,
  terraformDest: string,
  filePath?: string
): void {
  const configPath = filePath ?? resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      config =
        (yaml.load(fs.readFileSync(configPath, 'utf-8')) as IacToolboxYaml) ||
        {};
    } catch {
      config = {};
    }
  }

  config.threshold_alerts = {
    ...(config.threshold_alerts || {}),
    threshold_alerts_terraform_dest: terraformDest,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}

/**
 * Load whether threshold alerts are enabled from iac-toolbox.yml.
 * Returns undefined if not set.
 */
export function loadThresholdAlertsEnabled(
  destination: string,
  filePath?: string
): boolean | undefined {
  const config = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  return config.threshold_alerts?.enabled;
}

/**
 * Update the threshold_alerts.enabled key in iac-toolbox.yml.
 * Preserves the rest of the file content.
 */
export function updateThresholdAlertsConfig(
  destination: string,
  enabled: boolean
): void {
  const configPath = resolveConfigPath(destination);
  let config: IacToolboxYaml = {};

  if (fs.existsSync(configPath)) {
    try {
      config =
        (yaml.load(fs.readFileSync(configPath, 'utf-8')) as IacToolboxYaml) ||
        {};
    } catch {
      config = {};
    }
  }

  config.threshold_alerts = {
    ...(config.threshold_alerts || {}),
    enabled,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(config, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
