import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';
import {
  setCredential,
  getCredential,
} from '../../loaders/credentials-loader.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  postgresql?: {
    enabled?: boolean;
    port?: number;
    database?: string;
    version?: string;
    [key: string]: unknown;
  };
}

export interface PostgresqlConfig {
  enabled: boolean;
  port: number;
  database: string;
  version: string;
}

export function loadPostgresqlConfig(
  destination: string,
  filePath?: string
): PostgresqlConfig {
  const raw = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  const pg = raw.postgresql ?? {};
  return {
    enabled: pg.enabled ?? true,
    port: pg.port ?? 5432,
    database: pg.database ?? 'postgres',
    version: pg.version ?? '16',
  };
}

export function loadPostgresPassword(profile = 'default'): string | undefined {
  return getCredential('postgres_password', profile);
}

export function updatePostgresqlConfig(
  destination: string,
  config: PostgresqlConfig,
  password: string,
  profile = 'default',
  filePath?: string
): void {
  const configPath = filePath
    ? path.resolve(filePath)
    : resolveConfigPath(destination);

  let existing: IacToolboxYaml = {};
  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      existing = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      existing = {};
    }
  }

  // Save password to credentials store — never written to YAML file.
  setCredential('postgres_password', password, profile);

  existing.postgresql = {
    ...(existing.postgresql || {}),
    enabled: config.enabled,
    port: config.port,
    database: config.database,
    version: config.version,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(existing, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
