---
# ============================================
# IaC Toolbox - GitHub Playbook
# ============================================

- name: Deploy GitHub Build Workflow
  hosts: all
  become: false
  roles:
    - role: github-build-workflow
      when: github_build_workflow is defined and github_build_workflow.enabled
