---
# ============================================
# IaC Toolbox - Prometheus Playbook
# ============================================

- name: Deploy Prometheus
  hosts: all
  become: false
  roles:
    - role: prometheus
      when: prometheus is defined and prometheus.enabled
