import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import {
  loadIacToolboxYaml,
  resolveConfigPath,
} from 'src/loaders/yaml-loader.js';
import {
  setCredential,
  getCredential,
} from '../../loaders/credentials-loader.js';

interface IacToolboxYaml {
  [key: string]: unknown;
  pg_vector?: {
    enabled?: boolean;
    port?: number;
    database?: string;
    version?: string;
    [key: string]: unknown;
  };
}

export interface PgVectorConfig {
  enabled: boolean;
  port: number;
  database: string;
  version: string;
}

export function loadPgVectorConfig(
  destination: string,
  filePath?: string
): PgVectorConfig {
  const raw = loadIacToolboxYaml(destination, filePath) as IacToolboxYaml;
  const pgv = raw.pg_vector ?? {};
  return {
    enabled: pgv.enabled ?? true,
    port: pgv.port ?? 5433,
    database: pgv.database ?? 'pgvector',
    version: pgv.version ?? '16',
  };
}

export function loadPgVectorPassword(profile = 'default'): string | undefined {
  return getCredential('pgvector_password', profile);
}

export function updatePgVectorConfig(
  destination: string,
  config: PgVectorConfig,
  password: string,
  profile = 'default',
  filePath?: string
): void {
  const configPath = filePath
    ? path.resolve(filePath)
    : resolveConfigPath(destination);

  let existing: IacToolboxYaml = {};
  if (fs.existsSync(configPath)) {
    try {
      const content = fs.readFileSync(configPath, 'utf-8');
      existing = (yaml.load(content) as IacToolboxYaml) || {};
    } catch {
      existing = {};
    }
  }

  // Save password to credentials store — never written to YAML file.
  setCredential('pgvector_password', password, profile);

  existing.pg_vector = {
    ...(existing.pg_vector || {}),
    enabled: config.enabled,
    port: config.port,
    database: config.database,
    version: config.version,
  };

  const dir = path.dirname(configPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const yamlContent =
    '# Generated by iac-toolbox\n# Safe to commit — no secrets stored here\n' +
    yaml.dump(existing, { lineWidth: -1, quotingType: '"' });
  fs.writeFileSync(configPath, yamlContent, 'utf-8');
}
